on:
  issues:
    types: [opened]
jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'question')
    steps:
      - id: echo
        env:
          BODY: ${{ github.event.issue.body }}$$
        run: echo $BODY
      - if: >-
          (contains(github.event.issue.body, '- [x] I have asked the question on Stack Overflow and weighted 24 hours.')) != 'true'
        name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Please promise to follow the issue guide, and then replace `[ ]` by `[x]`.
# && contains(github.event.issue.body, '- [x] I have provided the link to the the question on Stack Overflow.') && contains(github.event.issue.body, '- [x] I have provided a reproducible example.'))
